### ISSUE TITLE
documentation error?

### ISSUE THREAD

**Issue by PFC-developer** [strangelove-ventures/horcrux#68]
Hi.
I'm doing a from-scratch install, and trying to following the instructions.

```
wget https://github.com/strangelove-ventures/horcrux/releases/download/v2.0.0-rc1/horcrux_2.0.0-rc1_linux_amd64.tar.gz
tar xfz horcrux_2.0.0-rc1_linux_amd64.tar.gz
mkdir bin
mv horcrux bin
mkdir /home/horcrux/.horcrux
horcrux config init ${CHAIN_ID} "tcp://${v_terra_hel_2}:1234" -c -p "tcp://${v_terra_hel_1}:2222|1,tcp://${v_terra_fsn_1}:2222|3" -l "tcp://${v_terra_hel_2}:2222" -t 2 --timeout 1500ms
```

produces the following
```
panic: open /home/horcrux/.horcrux/state/tcp:/write-file-atomic-07061320272504022285: no such file or directory

goroutine 1 [running]:
github.com/strangelove-ventures/horcrux/signer.(*SignState).save(0xc0000c6600)
        /home/runner/work/horcrux/horcrux/signer/sign_state.go:158 +0x119
github.com/strangelove-ventures/horcrux/signer.LoadOrCreateSignState(0xc0000fe5a0, 0x4f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/horcrux/horcrux/signer/sign_state.go:282 +0x1a7
github.com/strangelove-ventures/horcrux/cmd/horcrux/cmd.initCmd.func1(0xc0000fa280, 0xc0000f8c80, 0x1, 0xa, 0x0, 0x0)
        /home/runner/work/horcrux/horcrux/cmd/horcrux/cmd/config.go:144 +0x53d
github.com/spf13/cobra.(*Command).execute(0xc0000fa280, 0xc0000f8b40, 0xa, 0xa, 0xc0000fa280, 0xc0000f8b40)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x16e6160, 0x4012f0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/strangelove-ventures/horcrux/cmd/horcrux/cmd.Execute()
        /home/runner/work/horcrux/horcrux/cmd/horcrux/cmd/root.go:28 +0x2d
main.main()
        /home/runner/work/horcrux/horcrux/cmd/horcrux/main.go:21 +0x25
```

I'm unsure if it matters, but this is with terrad / rc-1

**Comment by agouin** [comment]
Please provide your vars `$CHAIN_ID`, `$v_terra_hel_2`, `$v_terra_hel_1`, and `$v_terra_fsn_1`.

I entered these vars, then pasted your command:
```bash
CHAIN_ID=columbus-5
v_terra_hel_2=192.168.4.3
v_terra_hel_1=192.168.4.4
v_terra_fsn_1=192.168.4.5
```

I did not see the panic.

Another thing, unless you are using port forwarding, I wouldn't expect `v_terra_hel_2` to be used for both the sentry IP/DNS and the horcrux signer 2 listen address:
- `"tcp://${v_terra_hel_2}:1234"` this argument should point to the sentry node running terrad. 
- `-l "tcp://${v_terra_hel_2}:2222"` this flag should be the listen address of the horcrux signer 2 node.

**Comment by PFC-developer** [comment]
```
export v_terra_hel_1=65.108.193.211
export v_terra_hel_2=65.108.193.210
export  v_terra_fsn_1=176.9.50.134

```

```
$ horcrux version

{
  "version": "",
  "commit": "",
  "go_version": "go1.16.14 linux/amd64",
  "cosmos_sdk_version": "",
  "tendermint_version": ""
}
```

and correct. I am running the signer & sentry on the same node at the moment. (I'm trying to reduce the # of machines/VMs required)

I will be moving to dockerized containers for horcurx but plan to run it on the same machine. Is this an issue?

**Comment by agouin** [comment]
Okay that makes sense. No problems running on the same machine. I tried with your vars too (assumed `$CHAIN_ID`) and still no issue.

```bash
wget https://github.com/strangelove-ventures/horcrux/releases/download/v2.0.0-rc1/horcrux_2.0.0-rc1_linux_amd64.tar.gz
tar xfz horcrux_2.0.0-rc1_linux_amd64.tar.gz
mkdir bin
mv horcrux bin
export PATH="$(pwd)/bin:$PATH"

export CHAIN_ID=columbus-5 # added this
export v_terra_hel_1=65.108.193.211
export v_terra_hel_2=65.108.193.210
export  v_terra_fsn_1=176.9.50.134
horcrux config init ${CHAIN_ID} "tcp://${v_terra_hel_2}:1234" -c -p "tcp://${v_terra_hel_1}:2222|1,tcp://${v_terra_fsn_1}:2222|3" -l "tcp://${v_terra_hel_2}:2222" -t 2 --timeout 1500ms
```

What is the OS?

**Comment by PFC-developer** [comment]
It's running ubu 20.04.
If it matters the other machines aren't running horcrux yet..I'm just going through the first machine's init

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by agouin** [comment]
Do you get the same issue if you copy/paste the entire snippet in my previous comment?

**Comment by PFC-developer** [comment]
no... 
bother now I can't reproduce it, on this or a second machine.

even with my initial values.

sorry for bugging you

**Comment by agouin** [comment]
No problem! Glad you have it working.
