### ISSUE TITLE
Raft does not elect a new leader after leader crash

### ISSUE THREAD

**Issue by Galadrin** [strangelove-ventures/horcrux#95]
After the Raft leader crashed, no new leader was elected by the cluster.

The issue happened after the disk of the signer get full.
```
Sep 13 13:09:42 signer-1 horcrux[51881]: panic: write /srv/injective/.horcrux/state/write-file-atomic-238428084346281919: no space left on device
Sep 13 13:09:42 signer-1 horcrux[51881]: goroutine 14099922 [running]:
Sep 13 13:09:42 signer-1 horcrux[51881]: github.com/strangelove-ventures/horcrux/signer.(*SignState).save(0xc000034b80)
Sep 13 13:09:42 signer-1 horcrux[51881]:         /home/runner/work/horcrux/horcrux/signer/sign_state.go:158 +0x119
Sep 13 13:09:42 signer-1 horcrux[51881]: github.com/strangelove-ventures/horcrux/signer.(*SignState).Save.func1(0xc000034b80)
Sep 13 13:09:42 signer-1 horcrux[51881]:         /home/runner/work/horcrux/horcrux/signer/sign_state.go:137 +0x2b
Sep 13 13:09:42 signer-1 horcrux[51881]: created by github.com/strangelove-ventures/horcrux/signer.(*SignState).Save
Sep 13 13:09:42 signer-1 horcrux[51881]:         /home/runner/work/horcrux/horcrux/signer/sign_state.go:136 +0x30c
```

removing the PID file and free some space allow the service to restart.

**Comment by agouin** [comment]
Do you by chance have logs from the other cosigners during this situation?

**Comment by Galadrin** [comment]
```
D[2022-09-13|15:09:39.867] I am not the raft leader. Proxying request to the leader module=validator
I[2022-09-13|15:09:40.075] Signed vote                                  module=validator node=tcp://[2a02:yyy:yyy:4875::1]:1235 height=15273528 round=0 type=SIGNED_MSG_TYPE_PREVOTE
D[2022-09-13|15:09:40.172] I am not the raft leader. Proxying request to the leader module=validator
I[2022-09-13|15:09:40.396] Signed vote                                  module=validator node=tcp://[2a02:yyy:yyy:4875::1]:1235 height=15273528 round=0 type=SIGNED_MSG_TYPE_PRECOMMIT
D[2022-09-13|15:09:41.678] I am not the raft leader. Proxying request to the leader module=validator
E[2022-09-13|15:09:42.104] Failed to sign vote                          module=validator address=tcp://[2a02:yyy:yyy:4875::1]:1235 error="rpc error: code = Unavailable desc = error reading fr>
D[2022-09-13|15:09:42.171] I am not the raft leader. Proxying request to the leader module=validator
E[2022-09-13|15:09:42.179] Failed to sign vote                          module=validator address=tcp://[2a02:yyy:yyy:4875::1]:1235 error="rpc error: code = Unavailable desc = connection error>
2022-09-13T15:09:43.150+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
D[2022-09-13|15:09:43.530] I am not the raft leader. Proxying request to the leader module=validator
2022-09-13T15:09:44.738+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
2022-09-13T15:09:46.333+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
E[2022-09-13|15:09:46.554] Failed to sign vote                          module=validator address=tcp://[2a02:yyy:yyy:4875::1]:1235 error="timed out waiting for leader election to complete" vo>
D[2022-09-13|15:09:46.812] I am not the raft leader. Proxying request to the leader module=validator
2022-09-13T15:09:47.764+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
2022-09-13T15:09:49.435+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
E[2022-09-13|15:09:49.833] Failed to sign vote                          module=validator address=tcp://[2a02:yyy:yyy:4875::1]:1235 error="timed out waiting for leader election to complete" vo>
D[2022-09-13|15:09:50.363] I am not the raft leader. Proxying request to the leader module=validator
2022-09-13T15:09:50.808+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
2022-09-13T15:09:51.973+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
E[2022-09-13|15:09:53.381] Failed to sign vote                          module=validator address=tcp://[2a02:yyy:yyy:4875::1]:1235 error="timed out waiting for leader election to complete" vo>
2022-09-13T15:09:53.857+0200 [ERROR] raft: failed to make requestVote RPC: target="{Voter 2 [2001:xxx:xxx:4f::1]:3333}" error="rpc error: code = Unavailable desc = connection error: desc = "tr>
```

**Comment by agouin** [comment]
Are these logs from signer 3? it appears that both 1 and 2 were unreachable during this time, so it looks like leader election failed because there wasn't a set of 2 nodes communicating.

**Comment by agouin** [comment]
Closing due to inactivity. Please reopen if you observe this again.
