### ISSUE TITLE
horcrux panic

### ISSUE THREAD

**Issue by PFC-developer** [strangelove-ventures/horcrux#96]
```

$ horcrux version
{
  "version": "2.0.0-rc3",
  "commit": "0f7cbf5eef6ab43cf22bc6b1ed5cde210605205a",
  "go_version": "go1.16.15 linux/amd64",
  "cosmos_sdk_version": "v0.44.5",
  "tendermint_version": "v0.34.14"
}

```
2nd & 3rd node are running
```
$ horcrux version
{
  "version": "2.0.0",
  "commit": "0ba5fda1d49ee18b2a452e94f8a9f29180776fd5",
  "go_version": "go1.16.15 linux/amd64",
  "cosmos_sdk_version": "v0.44.5",
  "tendermint_version": "v0.34.14"
}
```
1st node shows
LimitNOFILE=4096
```
Sep 14 18:05:24 n-hel-7 horcrux[1224842]: panic: open /home/horcrux_phoenix-1-xxx/.horcrux/state/write-file-atomic-08132135906461776673: too many open files
Sep 14 18:05:24 n-hel-7 horcrux[1224842]: goroutine 20740 [running]:
Sep 14 18:05:24 n-hel-7 horcrux[1224842]: github.com/strangelove-ventures/horcrux/signer.(*SignState).save(0xc000e90598)
Sep 14 18:05:24 n-hel-7 horcrux[1224842]:         /home/runner/work/horcrux/horcrux/signer/sign_state.go:158 +0x119
Sep 14 18:05:24 n-hel-7 horcrux[1224842]: github.com/strangelove-ventures/horcrux/signer.(*SignState).Save.func1(0xc000e90598)
Sep 14 18:05:24 n-hel-7 horcrux[1224842]:         /home/runner/work/horcrux/horcrux/signer/sign_state.go:137 +0x2b
Sep 14 18:05:24 n-hel-7 horcrux[1224842]: created by github.com/strangelove-ventures/horcrux/signer.(*SignState).Save
Sep 14 18:05:24 n-hel-7 horcrux[1224842]:         /home/runner/work/horcrux/horcrux/signer/sign_state.go:136 +0x30c
Sep 14 18:05:24 n-hel-7 systemd[1]: horcrux_phoenix-1-flipside.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 14 18:05:24 n-hel-7 systemd[1]: horcrux_phoenix-1-flipside.service: Failed with result 'exit-code'.
Sep 14 18:05:24 n-hel-7 systemd[1]: horcrux_phoenix-1-flipside.service: Consumed 2.116s CPU time.


```
2nd node just repeatedly shows (and shows 4/800%cpu on HTOP) 
LimitNOFILE=infinity (was 4096)
```
Sep 14 18:10:52 n-ovh-lim-02 horcrux[3070]: D[2022-09-14|18:10:52.403] I am not the raft leader. Proxying request to the leader module=validator
Sep 14 18:10:52 n-ovh-lim-02 horcrux[3070]: D[2022-09-14|18:10:52.403] I am not the raft leader. Proxying request to the leader module=validator
Sep 14 18:10:52 n-ovh-lim-02 horcrux[3070]: D[2022-09-14|18:10:52.404] I am not the raft leader. Proxying request to the leader module=validator
Sep 14 18:10:52 n-ovh-lim-02 horcrux[3070]: D[2022-09-14|18:10:52.404] I am not the raft leader. Proxying request to the leader module=validator
Sep 14 18:10:52 n-ovh-lim-02 horcrux[3070]: D[2022-09-14|18:10:52.405] I am not the raft leader. Proxying request to the leader module=validator
```

3rd node behaving properly (by the looks of it)
LimitNOFILE=4096 in .service file.

```
Sep 14 18:13:30 n-ovh-war-03 horcrux[577736]: I[2022-09-14|18:13:30.702] Signed vote                                  module=validator node=tcp://127.0.0.1:17097 height=1572925 round=0 type=SIGNED_MSG_TYPE_PRECOMMIT
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: D[2022-09-14|18:13:36.338] I am the raft leader. Managing the sign process for this block module=validator
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: D[2022-09-14|18:13:36.416] Have threshold peers                         module=validator
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: D[2022-09-14|18:13:36.416] Number of eph parts for peer                 module=validator peer=2 count=1
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: D[2022-09-14|18:13:36.416] Number of eph parts for peer                 module=validator peer=1 count=1
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: D[2022-09-14|18:13:36.426] Received signature from 1                    module=validator
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: D[2022-09-14|18:13:36.485] Received signature from 2                    module=validator
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: D[2022-09-14|18:13:36.485] Done waiting for cosigners, assembling signatures module=validator
Sep 14 18:13:36 n-ovh-war-03 horcrux[577736]: I[2022-09-14|18:13:36.508] Signed vote                                  module=validator node=tcp://127.0.0.1:17097 height=1572926 round=0 type=SIGNED_MSG_TYPE_PREVOTE

```

**Comment by PFC-developer** [comment]
tried

```
rm config.yaml
rm -rf raft/ 
```
on all nodes. no joy.

**Comment by PFC-developer** [comment]
as an update the nodes are now crashing and leaving the horcrux.pid file, making them non-restartable.

will have to remove horcrux from this validator, as it can't continue to sign without being supervised.

**Comment by PFC-developer** [comment]
apparently threatening to remove it caused it to behave.

I have absolutely no idea what happened, it is now behaving properly.

scares me tbh, as it went from failing badly every 15 minutes and requiring me to remove the horcrux.pid to suddenly working.

**Comment by agouin** [comment]
This appears to be the root cause

https://github.com/Jille/raft-grpc-transport/commit/8a9ada517787eb452529c981b62a39f0feb58502

**Comment by agouin** [comment]
Closing as stale
